function requireAll()
    wf = require("libraries/windfield")
    camera = require("libraries/camera")
    anim8 = require("libraries/anim8")
    require("tiledmap")
    require("src/player/player")
    require("src/player/playerCamera")
    require("src/npcs/NPC")
    require("src/npcs/npcs")
    require("src/npcs/Cow")
    require("src/npcs/Aurora")
    require("src/Inventory/Inventory")
    require("src/Inventory/Item")
    require("src/Inventory/Items")
    require("src/Inventory/inventoryHud")
    require("src/Inventory/Items/Pickaxe")
    require("utils")
end