function requireAll()
    wf = require("libraries/windfield")
    sti = require("libraries/sti")
    camera = require("libraries/camera")
    anim8 = require("libraries/anim8")
    require("map")
    require("tiledmap")
    require("player")
    require("playerCamera")
end