function requireAll()
    wf = require("libraries/windfield")
    camera = require("libraries/camera")
    anim8 = require("libraries/anim8")
    require("tiledmap")
    require("tiledmaps")
    require("src/player/player")
    require("src/player/playerCamera")
    require("src/entities/entities")
    require("src/entities/Entity")
    require("src/entities/Tree")
    require("src/entities/npcs/NPC")
    require("src/entities/npcs/Cow")
    require("src/entities/npcs/Aurora")
    require("src/Inventory/Inventory")
    require("src/Inventory/Item")
    require("src/Inventory/Items")
    require("src/Inventory/inventoryHud")
    require("src/Inventory/Items/Pickaxe")
    require("utils")
end